# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=120, verbose_name='执行命令名称')),
                ('result', models.CharField(max_length=120, verbose_name='执行结果')),
            ],
        ),
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('time', models.DateTimeField(max_length=30, verbose_name='时间')),
                ('job', models.CharField(max_length=120, verbose_name='任务')),
                ('note', models.CharField(max_length=300, verbose_name='备注')),
                ('linux_user', models.CharField(max_length=16, verbose_name='linux用户')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='主机名称')),
                ('ip', models.CharField(max_length=16, verbose_name='ip')),
                ('version', models.CharField(max_length=132, verbose_name='版本')),
                ('ssh', models.CharField(max_length=16, verbose_name='ssh端口')),
                ('type', models.CharField(max_length=12, verbose_name='主机类型')),
                ('hosts_status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintain', '维修'), ('stop_use', '停用')], max_length=64, verbose_name='主机状态')),
                ('hosts_environment', models.CharField(choices=[('test', '测试'), ('developing', '开发'), ('pre_production ', '预生产'), ('production ', '生产')], max_length=64, verbose_name='主机环境')),
            ],
        ),
        migrations.CreateModel(
            name='HostIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=30, verbose_name='主机发布时间')),
                ('host_issue_status', models.CharField(choices=[('wait_issue', '等待发布'), ('issueing', '发布中'), ('wait_test', '等待测试'), ('pass_test', '测试通过'), ('issue_success', '发布成功'), ('roll_back', '回滚')], max_length=64, verbose_name='主机发布状态')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host', verbose_name='主机信息')),
            ],
        ),
        migrations.CreateModel(
            name='Init',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_name', models.CharField(max_length=30, verbose_name='初始化名称')),
                ('system', models.CharField(max_length=50, verbose_name='系统名称')),
                ('init_function', models.CharField(max_length=200, verbose_name='初始化功能')),
                ('playbook', models.CharField(max_length=20, verbose_name='playbook')),
                ('init_time', models.DateTimeField(max_length=20, verbose_name='初始化时间')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=50, verbose_name='版本号')),
                ('issue_status', models.CharField(choices=[('wait_issue', '等待发布'), ('issueing', '发布中'), ('wait_test', '等待测试'), ('pass_test', '测试通过'), ('issue_success', '发布成功'), ('roll_back', '回滚')], max_length=64, verbose_name='发布状态')),
                ('file_dir', models.CharField(max_length=50, verbose_name='部署发布系统')),
                ('backups', models.CharField(choices=[('yes', '已备份'), ('no', '未备份')], max_length=64, verbose_name='备份情况')),
                ('backup_path', models.CharField(max_length=30, verbose_name='备份地址')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名称')),
            ],
        ),
        migrations.CreateModel(
            name='TeamProjt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('create_time', models.DateTimeField(max_length=50, verbose_name='项目创建时间')),
                ('develop_language', models.CharField(max_length=20, verbose_name='开发语言')),
                ('team_status', models.CharField(choices=[('in_use', '在用'), ('off_line', '下线')], max_length=64, verbose_name='项目状态')),
                ('nginx_conf', models.CharField(max_length=254, verbose_name='nginx配置信息')),
                ('project_path', models.CharField(max_length=60, verbose_name='linux项目路径')),
                ('git_path', models.CharField(max_length=80, verbose_name='git地址')),
                ('note', models.CharField(max_length=300, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='用户名')),
                ('password', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('develop', '开发'), ('operation', '运维'), ('test', '测试')], max_length=20, verbose_name='部门')),
                ('create_time', models.DateTimeField(max_length=50, verbose_name='创建时间')),
                ('role', models.ManyToManyField(to='web.Role')),
            ],
        ),
        migrations.AddField(
            model_name='teamprojt',
            name='developer',
            field=models.ManyToManyField(related_name='开发人', to='web.User', verbose_name='开发人'),
        ),
        migrations.AddField(
            model_name='teamprojt',
            name='nginx_host',
            field=models.ManyToManyField(related_name='nginx服务器', to='web.Host', verbose_name='nginx服务器'),
        ),
        migrations.AddField(
            model_name='teamprojt',
            name='principal',
            field=models.ManyToManyField(related_name='负责人', to='web.User', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='teamprojt',
            name='server_host',
            field=models.ManyToManyField(related_name='其他服务器', to='web.Host', verbose_name='其他服务器'),
        ),
        migrations.AddField(
            model_name='teamprojt',
            name='tester',
            field=models.ManyToManyField(related_name='测试人', to='web.User', verbose_name='测试人'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TeamProjt', verbose_name='发布项目'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='hostissue',
            name='innues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Issue', verbose_name='发布信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='inits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Init'),
        ),
        migrations.AddField(
            model_name='cron',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='command',
            name='host_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host', verbose_name='主机列表'),
        ),
        migrations.AddField(
            model_name='command',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='执行人'),
        ),
    ]
