# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-21 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190421_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cron',
            old_name='linux_user',
            new_name='user',
        ),
    ]
