# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190421_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='init',
            old_name='function',
            new_name='func',
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='teamprojt',
            name='project_path',
            field=models.CharField(max_length=200, verbose_name='项目目录'),
        ),
    ]
